
name: day1-ci-basics

on:
  push:
    branches: [ day1 ]
  workflow_dispatch:

jobs:
   build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Hello
        run: echo "hello from github"

      - name: test context
        run : echo '${{toJson(github)}}'        
