
name: day1-ci-basics

on:
  push:
    branches: [ day1 ]
  workflow_dispatch:
env:
  APP_ENV: dev
  OWNER: Jayesh

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Hello
        run: echo "hello from github"

      - name: test context
        run: echo '${{ toJson(github) }}'
        
      - name: test env
        run: |
          echo "Environment : ${{ env.APP_ENV }}, Owner: ${{ env.OWNER }}"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Print Node version
        run: node --version
    